import { Inter } from "next/font/google";

import "./style.css";

import { Toaster } from "@/components/ui/toaster";

import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next template admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className={inter.className}>
      {children}
      <Toaster />
    </main>
  );
}
